name: Emulate latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  emulation:
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
        env:
          USER: tvorogme

      - name: Download emulator
        run: |
          sudo apt update -y
          sudo apt install -y wget git
          wget https://dton.io/media/libemulator.so
          mv libemulator.so /tmp/libemulator.so

      - name: Install deps
        run: python -m pip install git+https://github.com/disintar/tonemuso.git

      - name: LS - Run emulation only MC
        run: |
          touch failed_txs.json
          tonemuso
          mv ./failed_txs.json /tmp
        env:
          LITESERVER_SERVER: ${{ secrets.LITESERVER_SERVER }}
          LITESERVER_PORT: ${{ secrets.LITESERVER_PORT }}
          LITESERVER_PUBKEY: ${{ secrets.LITESERVER_PUBKEY }}
          EMULATOR_PATH: "/tmp/libemulator.so"
          NPROC: 40
          FROM_SEQNO: 36305863
          TO_SEQNO: 36306863
          CHUNK_SIZE: 1000
          PARSE_OVER_LS: 1
          ONLYMC_BLOCK: 1
          EMUSO_LOGLEVEL: 2
          TX_CHUNK_SIZE: 10000
          C7_REWRITE: '{"20": "te6ccuEBAQEATACYAJTRAAAAAAAAAGQAAAAAAJiWgN4AAAAAA+gAAAAAAAAAD0JAAAAAAAAPQkAAAAAAAAAnEAAAAAAAmJaAAAAAAAX14QAAAAAAO5rKAIvKAZs=", "21": "te6ccuEBAQEATACYAJTRAAAAAAAAAGQAAAAAAJiWgN4AAAAAA+gAAAAAAAAAD0JAAAAAAAAPQkAAAAAAAAAnEAAAAAAAmJaAAAAAAAX14QAAAAAAO5rKAIvKAZs="}'

      - name: BLOCK - Run emulation only MC
        run: |
          touch failed_txs.json
          tonemuso
          mv ./failed_txs.json /tmp
        env:
          LITESERVER_SERVER: ${{ secrets.LITESERVER_SERVER }}
          LITESERVER_PORT: ${{ secrets.LITESERVER_PORT }}
          LITESERVER_PUBKEY: ${{ secrets.LITESERVER_PUBKEY }}
          EMULATOR_PATH: "/tmp/libemulator.so"
          NPROC: 40
          FROM_SEQNO: 36305863
          TO_SEQNO: 36306863
          CHUNK_SIZE: 1000
          PARSE_OVER_LS: 0
          ONLYMC_BLOCK: 1
          EMUSO_LOGLEVEL: 2
          TX_CHUNK_SIZE: 10000
          C7_REWRITE: '{"20": "te6ccuEBAQEATACYAJTRAAAAAAAAAGQAAAAAAJiWgN4AAAAAA+gAAAAAAAAAD0JAAAAAAAAPQkAAAAAAAAAnEAAAAAAAmJaAAAAAAAX14QAAAAAAO5rKAIvKAZs=", "21": "te6ccuEBAQEATACYAJTRAAAAAAAAAGQAAAAAAJiWgN4AAAAAA+gAAAAAAAAAD0JAAAAAAAAPQkAAAAAAAAAnEAAAAAAAmJaAAAAAAAX14QAAAAAAO5rKAIvKAZs="}'

      - name: LS - Run emulation
        run: |
          touch failed_txs.json
          tonemuso
          mv ./failed_txs.json /tmp
        env:
          LITESERVER_SERVER: ${{ secrets.LITESERVER_SERVER }}
          LITESERVER_PORT: ${{ secrets.LITESERVER_PORT }}
          LITESERVER_PUBKEY: ${{ secrets.LITESERVER_PUBKEY }}
          EMULATOR_PATH: "/tmp/libemulator.so"
          FROM_SEQNO: 36305863
          TO_SEQNO: 36306863
          PARSE_OVER_LS: 1
          NPROC: 40
          CHUNK_SIZE: 1000
          TX_CHUNK_SIZE: 10000

      - name: BLOCK - Run emulation
        run: |
          touch failed_txs.json
          tonemuso
          mv ./failed_txs.json /tmp
        env:
          LITESERVER_SERVER: ${{ secrets.LITESERVER_SERVER }}
          LITESERVER_PORT: ${{ secrets.LITESERVER_PORT }}
          LITESERVER_PUBKEY: ${{ secrets.LITESERVER_PUBKEY }}
          EMULATOR_PATH: "/tmp/libemulator.so"
          FROM_SEQNO: 36305863
          TO_SEQNO: 36306863
          PARSE_OVER_LS: 0
          NPROC: 40
          CHUNK_SIZE: 1000
          TX_CHUNK_SIZE: 10000
#
#      - name: LS - 50k
#        run: |
#          touch failed_txs.json
#          tonemuso
#          mv ./failed_txs.json /tmp
#        env:
#          LITESERVER_SERVER: ${{ secrets.LITESERVER_SERVER }}
#          LITESERVER_PORT: ${{ secrets.LITESERVER_PORT }}
#          LITESERVER_PUBKEY: ${{ secrets.LITESERVER_PUBKEY }}
#          EMULATOR_PATH: "/tmp/libemulator.so"
#          FROM_SEQNO: 36256863
#          TO_SEQNO: 36306863
#          PARSE_OVER_LS: 1
#          NPROC: 40
#          CHUNK_SIZE: 1000
#          TX_CHUNK_SIZE: 40000
#
#      - name: BLOCK - 50k
#        run: |
#          touch failed_txs.json
#          tonemuso
#          mv ./failed_txs.json /tmp
#        env:
#          LITESERVER_SERVER: ${{ secrets.LITESERVER_SERVER }}
#          LITESERVER_PORT: ${{ secrets.LITESERVER_PORT }}
#          LITESERVER_PUBKEY: ${{ secrets.LITESERVER_PUBKEY }}
#          EMULATOR_PATH: "/tmp/libemulator.so"
#          FROM_SEQNO: 36256863
#          TO_SEQNO: 36306863
#          PARSE_OVER_LS: 0
#          NPROC: 40
#          CHUNK_SIZE: 1000
#          TX_CHUNK_SIZE: 40000

      - uses: actions/upload-artifact@v4
        with:
          name: failed_txs
          path: /tmp/failed_txs.json
