name: Emulate latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    name:
    runs-on: tonemuso

    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
        env:
          USER: tvorogme

      - name: Download emulator
        run: wget https://dton.io/media/libemulator.so && mv libemulator.so /tmp/libemulator.so

      - name: Install deps
        run: python -m pip install git+https://github.com/disintar/tonemuso.git

      - name: Run emulation
        run: |
          tonemuso
        env:
          LITESERVER_SERVER: ${{ secrets.LITESERVER_SERVER }}
          LITESERVER_PORT: ${{ secrets.LITESERVER_PORT }}
          LITESERVER_PUBKEY: ${{ secrets.LITESERVER_PUBKEY }}
          EMULATOR_PATH: "/tmp/libemulator.so"
          TO_EMULATE_MC_BLOCKS: 100
          NPROC: 40
          CHUNK_SIZE: 10
